//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1891
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetRadio.LocatingMonitor {
    
    
    public partial class @__Home0 {
        
        /// <summary>
        /// collapseView 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::NetRadio.Assistant.Web.Controls.CollapseView collapseView;
        
        /// <summary>
        /// RepGroup 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater RepGroup;
        
        /// <summary>
        /// newEventCount 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::NetRadio.Assistant.Web.Controls.NumericLabel newEventCount;
        
        /// <summary>
        /// logFromDate 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::NetRadio.Assistant.Web.Controls.DateTimeLabel logFromDate;
        
        /// <summary>
        /// logCount 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::NetRadio.Assistant.Web.Controls.NumericLabel logCount;
        
        /// <summary>
        /// lowBatteryFromDate 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::NetRadio.Assistant.Web.Controls.DateTimeLabel lowBatteryFromDate;
        
        /// <summary>
        /// lowBatteryCount 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::NetRadio.Assistant.Web.Controls.NumericLabel lowBatteryCount;
        
        /// <summary>
        /// apCount 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::NetRadio.Assistant.Web.Controls.NumericLabel apCount;
        
        /// <summary>
        /// apFailedCount 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::NetRadio.Assistant.Web.Controls.NumericLabel apFailedCount;
    }
}
