//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetRadio.LocatingMonitor.Organize {
    
    
    public partial class @__MapAreaList {

        /// <summary>
        /// objectNavigator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NetRadio.LocatingMonitor.Controls.@__ObjectNavigator objectNavigator;
        
        /// <summary>
        /// filterView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NetRadio.Assistant.Web.Controls.CollapseView filterView;
        
        /// <summary>
        /// maps control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NetRadio.LocatingMonitor.Controls.FacilityMapDropList maps;
        
        /// <summary>
        /// filterButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button filterButton;
        
        /// <summary>
        /// removeCache control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton removeCache;
        
        /// <summary>
        /// collapseView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NetRadio.Assistant.Web.Controls.CollapseView collapseView;
        
        /// <summary>
        /// areaList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater areaList;
        
        /// <summary>
        /// p control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NetRadio.Assistant.Web.Controls.Pagination p;
    }
}
