<%@ Page Language="C#" MasterPageFile="~/Default.Master" AutoEventWireup="true" CodeBehind="TagUser.aspx.cs" Inherits="NetRadio.LocatingMonitor.TagUsers.__TagUser"%>
<asp:Content ID="Content1" ContentPlaceHolderID="CphRight" runat="server">Page Layout .....
</asp:Content>
